### ISSUE TITLE
OverParse spitting out errors on start-up

### ISSUE THREAD

**Issue by JaneSmith** [TyroneSama/OverParse#10]
OverParse has been great for a long time, but now it's crashing sometimes and spitting out errors when I start it up:

> Oops. This is embarassing.
> 
> OverParse encountered an unexpected error. If this happens again, please complain to TyroneSama at your earliest convenience. Include your log from OverParse\logs and the following message:
> 
> The invocation of the constructor on type 'OverParse.MainWindow' that matches the specified binding constraints threw an exception.
> 
> Sorry for the inconvenience!

There doesn't appear to actually be any saved error log though.

**Comment by TyroneSama** [comment]
Sorry, this has been unmaintained for a few thousand years because I no longer play. I recommend looking into one of the maintained forks—[Remon's](https://github.com/Remon-7L/OverParse/) seems to be fairly popular.

**Comment by JaneSmith** [comment]
Thanks. Could you perhaps update the README to point to that fork? I'd never heard of it before and had no idea there were better maintained forks.
