### ISSUE TITLE
Feature Request: Compact Mode

### ISSUE THREAD

**Issue by ryanelian** [TyroneSama/OverParse#3]
Most times I don't care about other people's max hit, only mine.

It would be nice to have an option to hide the max hit column (So the window can be smaller without reducing visual on the damage and %DPS column), but still display the player's own max hit (suggested location: at the bottom alongside / replacing that time / DPS counter?)

Thanks in advance!

**Comment by TyroneSama** [comment]
Oh, hey. I actually pushed a commit that added this before I even noticed this issue. You're in luck!

I'll update it to add your suggestion regarding the player's max hit.

**Comment by ryanelian** [comment]
That's so epic. High five o/**\o

**Comment by TyroneSama** [comment]
\o
